//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eipProjectDetail
    {
        public int pjId { get; set; }
        public string pjName { get; set; }
        public string pjManager { get; set; }
        public string pjDate { get; set; }
        public string pjContent專案內容 { get; set; }
        public string pjPV預算 { get; set; }
        public string pjAC實際成本 { get; set; }
        public string pjEV淨利 { get; set; }
        public Nullable<int> pjReviewAcceptOrNot1 { get; set; }
        public Nullable<int> pjReviewAcceptOrNot2 { get; set; }
        public Nullable<int> pjReviewAcceptOrNot3 { get; set; }
        public Nullable<int> pjReviewLevel { get; set; }
        public string pjReviewAdvise1 { get; set; }
        public string pjReviewAdvise2 { get; set; }
        public string pjReviewAdvise3 { get; set; }
        public Nullable<decimal> pj廠商投標金額 { get; set; }
        public string pj項目 { get; set; }
        public Nullable<int> pjDailyReport { get; set; }
    
        public virtual projectTeam projectTeam { get; set; }
    }
}
