//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoomBooking
    {
        public int BookingId { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string 中文姓名 { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingStartTime { get; set; }
        public string BookingEndTime { get; set; }
        public Nullable<int> MeetingRoomId { get; set; }
        public string MeetingRoomName { get; set; }
        public string MeetingRemark { get; set; }
        public string MeetingSubject { get; set; }
        public string MeetingAttentee { get; set; }
    }
}
