//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectTeam
    {
        public int pjDailyReport { get; set; }
        public string pjTeam { get; set; }
        public Nullable<int> pjId { get; set; }
        public Nullable<int> employeeID { get; set; }
        public string pjJob { get; set; }
        public Nullable<int> pj人數 { get; set; }
        public Nullable<int> pj開始時間 { get; set; }
        public Nullable<int> pj結束時間 { get; set; }
        public string pj工作內容 { get; set; }
        public Nullable<int> pj工作時間 { get; set; }
        public string pj填表日期 { get; set; }
    
        public virtual eipProjectDetail eipProjectDetail { get; set; }
        public virtual 個人資料 個人資料 { get; set; }
    }
}
