//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 個人資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 個人資料()
        {
            this.projectTeam = new HashSet<projectTeam>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeePW { get; set; }
        public string 受雇日期 { get; set; }
        public string 中文姓名 { get; set; }
        public string 英文姓名 { get; set; }
        public string 職稱 { get; set; }
        public string 狀態 { get; set; }
        public string 部門 { get; set; }
        public string 性別 { get; set; }
        public string 出生年月日 { get; set; }
        public string 信箱 { get; set; }
        public string 電話 { get; set; }
        public string 居住地 { get; set; }
        public string 婚姻狀況 { get; set; }
        public string 薪資 { get; set; }
        public string 特休 { get; set; }
        public Nullable<int> 權限 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectTeam> projectTeam { get; set; }
    }
}
