//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 工作清單
    {
        public int EmployeeID { get; set; }
        public string 專案歸類 { get; set; }
        public string 重要性 { get; set; }
        public string 事項名稱 { get; set; }
        public string 回報狀況 { get; set; }
        public string 完成度 { get; set; }
        public string 交辦人 { get; set; }
        public string 完成日 { get; set; }
    }
}
